/** LLM 工厂枚举 - 与前台保持一致 */
export enum LLMFactory {
    TongYiQianWen = 'Tongyi-Qianwen',
    Moonshot = 'Moonshot',
    OpenAI = 'OpenAI',
    ZhipuAI = 'ZHIPU-AI',
    WenXinYiYan = '文心一言',
    Ollama = 'Ollama',
    Xinference = 'Xinference',
    ModelScope = 'ModelScope',
    DeepSeek = 'DeepSeek',
    VolcEngine = 'VolcEngine',
    BaiChuan = 'BaiChuan',
    Jina = 'Jina',
    MiniMax = 'MiniMax',
    Mistral = 'Mistral',
    AzureOpenAI = 'Azure-OpenAI',
    Bedrock = 'Bedrock',
    Gemini = 'Gemini',
    Groq = 'Groq',
    OpenRouter = 'OpenRouter',
    LocalAI = 'LocalAI',
    StepFun = 'StepFun',
    NVIDIA = 'NVIDIA',
    LMStudio = 'LM-Studio',
    OpenAiAPICompatible = 'OpenAI-API-Compatible',
    Cohere = 'Cohere',
    LeptonAI = 'LeptonAI',
    TogetherAI = 'TogetherAI',
    PerfXCloud = 'PerfXCloud',
    Upstage = 'Upstage',
    NovitaAI = 'novita.ai',
    SILICONFLOW = 'SILICONFLOW',
    PPIO = 'PPIO',
    ZeroOneAI = '01.AI',
    Replicate = 'Replicate',
    TencentHunYuan = 'Tencent Hunyuan',
    XunFeiSpark = 'XunFei Spark',
    BaiduYiYan = 'BaiduYiyan',
    FishAudio = 'Fish Audio',
    TencentCloud = 'Tencent Cloud',
    Anthropic = 'Anthropic',
    VoyageAI = 'Voyage AI',
    GoogleCloud = 'Google Cloud',
    HuggingFace = 'HuggingFace',
    YouDao = 'Youdao',
    BAAI = 'BAAI',
    NomicAI = 'nomic-ai',
    JinaAI = 'jinaai',
    SentenceTransformers = 'sentence-transformers',
    GPUStack = 'GPUStack',
    VLLM = 'VLLM',
}

/** 图标映射 */
export const IconMap: Record<string, string> = {
    [LLMFactory.TongYiQianWen]: 'tongyi',
    [LLMFactory.Moonshot]: 'moonshot',
    [LLMFactory.OpenAI]: 'openai',
    [LLMFactory.ZhipuAI]: 'zhipu',
    [LLMFactory.WenXinYiYan]: 'wenxin',
    [LLMFactory.Ollama]: 'ollama',
    [LLMFactory.Xinference]: 'xinference',
    [LLMFactory.ModelScope]: 'modelscope',
    [LLMFactory.DeepSeek]: 'deepseek',
    [LLMFactory.VolcEngine]: 'volc_engine',
    [LLMFactory.BaiChuan]: 'baichuan',
    [LLMFactory.Jina]: 'jina',
    [LLMFactory.MiniMax]: 'chat-minimax',
    [LLMFactory.Mistral]: 'mistral',
    [LLMFactory.AzureOpenAI]: 'azure',
    [LLMFactory.Bedrock]: 'bedrock',
    [LLMFactory.Gemini]: 'gemini',
    [LLMFactory.Groq]: 'groq-next',
    [LLMFactory.OpenRouter]: 'open-router',
    [LLMFactory.LocalAI]: 'local-ai',
    [LLMFactory.StepFun]: 'stepfun',
    [LLMFactory.NVIDIA]: 'nvidia',
    [LLMFactory.LMStudio]: 'lm-studio',
    [LLMFactory.OpenAiAPICompatible]: 'openai-api',
    [LLMFactory.Cohere]: 'cohere',
    [LLMFactory.LeptonAI]: 'lepton-ai',
    [LLMFactory.TogetherAI]: 'together-ai',
    [LLMFactory.PerfXCloud]: 'perfx-cloud',
    [LLMFactory.Upstage]: 'upstage',
    [LLMFactory.NovitaAI]: 'novita-ai',
    [LLMFactory.SILICONFLOW]: 'siliconflow',
    [LLMFactory.PPIO]: 'ppio',
    [LLMFactory.ZeroOneAI]: 'yi',
    [LLMFactory.Replicate]: 'replicate',
    [LLMFactory.TencentHunYuan]: 'hunyuan',
    [LLMFactory.XunFeiSpark]: 'spark',
    [LLMFactory.BaiduYiYan]: 'yiyan',
    [LLMFactory.FishAudio]: 'fish-audio',
    [LLMFactory.TencentCloud]: 'tencent-cloud',
    [LLMFactory.Anthropic]: 'anthropic',
    [LLMFactory.VoyageAI]: 'voyage',
    [LLMFactory.GoogleCloud]: 'google-cloud',
    [LLMFactory.HuggingFace]: 'huggingface',
    [LLMFactory.YouDao]: 'youdao',
    [LLMFactory.BAAI]: 'baai',
    [LLMFactory.NomicAI]: 'nomic-ai',
    [LLMFactory.JinaAI]: 'jina',
    [LLMFactory.SentenceTransformers]: 'sentence-transformers',
    [LLMFactory.GPUStack]: 'gpustack',
    [LLMFactory.VLLM]: 'vllm',
}

/** 本地部署的 LLM 工厂列表 */
export const LocalLlmFactories = [
    LLMFactory.Ollama,
    LLMFactory.Xinference,
    LLMFactory.LocalAI,
    LLMFactory.LMStudio,
    LLMFactory.GPUStack,
    LLMFactory.VLLM,
    LLMFactory.HuggingFace,
    LLMFactory.TogetherAI,
    LLMFactory.OpenRouter,
    LLMFactory.OpenAiAPICompatible,
    LLMFactory.Replicate,
    LLMFactory.ModelScope,
]

/** 需要特殊表单的工厂 */
export const SpecialFormFactories = [
    LLMFactory.VolcEngine,
    LLMFactory.TencentHunYuan,
    LLMFactory.TencentCloud,
    LLMFactory.Bedrock,
    LLMFactory.GoogleCloud,
    LLMFactory.XunFeiSpark,
    LLMFactory.BaiduYiYan,
    LLMFactory.FishAudio,
    LLMFactory.AzureOpenAI,
]

/** Bedrock 区域列表 */
export const BedrockRegionList = [
    'us-east-1',
    'us-east-2',
    'us-west-1',
    'us-west-2',
    'af-south-1',
    'ap-east-1',
    'ap-south-1',
    'ap-northeast-1',
    'ap-northeast-2',
    'ap-northeast-3',
    'ap-southeast-1',
    'ap-southeast-2',
    'ap-southeast-3',
    'ca-central-1',
    'eu-central-1',
    'eu-west-1',
    'eu-west-2',
    'eu-west-3',
    'eu-north-1',
    'eu-south-1',
    'me-south-1',
    'me-central-1',
    'sa-east-1',
]

/** 判断是否为本地部署工厂 */
export function isLocalLlmFactory(factory: string): boolean {
    return LocalLlmFactories.includes(factory as LLMFactory)
}

/** 判断是否需要特殊表单 */
export function isSpecialFormFactory(factory: string): boolean {
    return SpecialFormFactories.includes(factory as LLMFactory)
}
